site_name: MAGUI
site_url: https://codedoctorde.tk/MAGUI
repo_url: https://github.com/codedoctorde/MAGUI/
theme:
  name: 'material'
  palette:
    scheme: 'slate' # Add this
markdown_extensions:
  - codehilite
nav:
  - Home: README.md